### ISSUE TITLE
Reference to missing service puppetboard

### ISSUE THREAD

**Issue by alvagante** [voxpupuli/puppet-module-puppetboard#58]
If you set listen => 'public' you get an invalid relationships error since Service[puppetboard] seems not to be defined anywhere.
https://github.com/puppet-community/puppet-module-puppetboard/blob/master/manifests/init.pp#L246

**Comment by ghoneycutt** [comment]
@nibalizer This bit me today. No luck getting puppetboard going at all using this module. Perhaps you could post a gist of the code/hiera data that works for you? I'm happy to add support for EL 6 once I can get it working in some fashion.

**Comment by nibalizer** [comment]
ah hrm. We should fix this...

**Comment by jyaworski** [comment]
Is this still a problem?

**Comment by mattock** [comment]
Yes, this is still a problem. I hit it today when installing puppetboard. Can't the notify just be removed?

**Comment by jyaworski** [comment]
I just removed the notify line. Let me know if it breaks anything.
